# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/query/v1beta1/params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.gov.v1 import query_pb2 as cosmos_dot_gov_dot_v1_dot_query__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from kyve.bundles.v1beta1 import params_pb2 as kyve_dot_bundles_dot_v1beta1_dot_params__pb2
from kyve.delegation.v1beta1 import params_pb2 as kyve_dot_delegation_dot_v1beta1_dot_params__pb2
import importlib
kyve_dot_global_dot_v1beta1_dot_global__pb2 = importlib.import_module('kyve.global.v1beta1.global_pb2')
from kyve.stakers.v1beta1 import params_pb2 as kyve_dot_stakers_dot_v1beta1_dot_params__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/query/v1beta1/params.proto',
  package='kyve.query.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n\x1fkyve/query/v1beta1/params.proto\x12\x12kyve.query.v1beta1\x1a\x19\x63osmos/gov/v1/query.proto\x1a\x1cgoogle/api/annotations.proto\x1a!kyve/bundles/v1beta1/params.proto\x1a$kyve/delegation/v1beta1/params.proto\x1a kyve/global/v1beta1/global.proto\x1a!kyve/stakers/v1beta1/params.proto\"\x14\n\x12QueryParamsRequest\"\xa9\x02\n\x13QueryParamsResponse\x12\x34\n\x0e\x62undles_params\x18\x01 \x01(\x0b\x32\x1c.kyve.bundles.v1beta1.Params\x12:\n\x11\x64\x65legation_params\x18\x02 \x01(\x0b\x32\x1f.kyve.delegation.v1beta1.Params\x12\x32\n\rglobal_params\x18\x03 \x01(\x0b\x32\x1b.kyve.global.v1beta1.Params\x12\x36\n\ngov_params\x18\x04 \x01(\x0b\x32\".cosmos.gov.v1.QueryParamsResponse\x12\x34\n\x0estakers_params\x18\x05 \x01(\x0b\x32\x1c.kyve.stakers.v1beta1.Params2\x8c\x01\n\x0bQueryParams\x12}\n\x06Params\x12&.kyve.query.v1beta1.QueryParamsRequest\x1a\'.kyve.query.v1beta1.QueryParamsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/kyve/query/v1beta1/paramsB,Z*github.com/KYVENetwork/chain/x/query/typesb\x06proto3')
  ,
  dependencies=[cosmos_dot_gov_dot_v1_dot_query__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,kyve_dot_bundles_dot_v1beta1_dot_params__pb2.DESCRIPTOR,kyve_dot_delegation_dot_v1beta1_dot_params__pb2.DESCRIPTOR,kyve_dot_global_dot_v1beta1_dot_global__pb2.DESCRIPTOR,kyve_dot_stakers_dot_v1beta1_dot_params__pb2.DESCRIPTOR,])




_QUERYPARAMSREQUEST = _descriptor.Descriptor(
  name='QueryParamsRequest',
  full_name='kyve.query.v1beta1.QueryParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=274,
)


_QUERYPARAMSRESPONSE = _descriptor.Descriptor(
  name='QueryParamsResponse',
  full_name='kyve.query.v1beta1.QueryParamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bundles_params', full_name='kyve.query.v1beta1.QueryParamsResponse.bundles_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delegation_params', full_name='kyve.query.v1beta1.QueryParamsResponse.delegation_params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_params', full_name='kyve.query.v1beta1.QueryParamsResponse.global_params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gov_params', full_name='kyve.query.v1beta1.QueryParamsResponse.gov_params', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stakers_params', full_name='kyve.query.v1beta1.QueryParamsResponse.stakers_params', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=574,
)

_QUERYPARAMSRESPONSE.fields_by_name['bundles_params'].message_type = kyve_dot_bundles_dot_v1beta1_dot_params__pb2._PARAMS
_QUERYPARAMSRESPONSE.fields_by_name['delegation_params'].message_type = kyve_dot_delegation_dot_v1beta1_dot_params__pb2._PARAMS
_QUERYPARAMSRESPONSE.fields_by_name['global_params'].message_type = kyve_dot_global_dot_v1beta1_dot_global__pb2._PARAMS
_QUERYPARAMSRESPONSE.fields_by_name['gov_params'].message_type = cosmos_dot_gov_dot_v1_dot_query__pb2._QUERYPARAMSRESPONSE
_QUERYPARAMSRESPONSE.fields_by_name['stakers_params'].message_type = kyve_dot_stakers_dot_v1beta1_dot_params__pb2._PARAMS
DESCRIPTOR.message_types_by_name['QueryParamsRequest'] = _QUERYPARAMSREQUEST
DESCRIPTOR.message_types_by_name['QueryParamsResponse'] = _QUERYPARAMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryParamsRequest = _reflection.GeneratedProtocolMessageType('QueryParamsRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPARAMSREQUEST,
  __module__ = 'kyve.query.v1beta1.params_pb2'
  # @@protoc_insertion_point(class_scope:kyve.query.v1beta1.QueryParamsRequest)
  ))
_sym_db.RegisterMessage(QueryParamsRequest)

QueryParamsResponse = _reflection.GeneratedProtocolMessageType('QueryParamsResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPARAMSRESPONSE,
  __module__ = 'kyve.query.v1beta1.params_pb2'
  # @@protoc_insertion_point(class_scope:kyve.query.v1beta1.QueryParamsResponse)
  ))
_sym_db.RegisterMessage(QueryParamsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z*github.com/KYVENetwork/chain/x/query/types'))

_QUERYPARAMS = _descriptor.ServiceDescriptor(
  name='QueryParams',
  full_name='kyve.query.v1beta1.QueryParams',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=577,
  serialized_end=717,
  methods=[
  _descriptor.MethodDescriptor(
    name='Params',
    full_name='kyve.query.v1beta1.QueryParams.Params',
    index=0,
    containing_service=None,
    input_type=_QUERYPARAMSREQUEST,
    output_type=_QUERYPARAMSRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\034\022\032/kyve/query/v1beta1/params')),
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERYPARAMS)

DESCRIPTOR.services_by_name['QueryParams'] = _QUERYPARAMS

# @@protoc_insertion_point(module_scope)
