# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/upgrades/v1beta1/old_params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/upgrades/v1beta1/old_params.proto',
  package='kyve.upgrades.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n&kyve/upgrades/v1beta1/old_params.proto\x12\x15kyve.upgrades.v1beta1\x1a\x14gogoproto/gogo.proto\"\x99\x01\n\x10OldBundlesParams\x12\x16\n\x0eupload_timeout\x18\x01 \x01(\x04\x12\x44\n\x0cstorage_cost\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x13\n\x0bnetwork_fee\x18\x03 \x01(\t\x12\x12\n\nmax_points\x18\x04 \x01(\x04\"\xb9\x01\n\x13OldDelegationParams\x12!\n\x19unbonding_delegation_time\x18\x01 \x01(\x04\x12\x1d\n\x15redelegation_cooldown\x18\x02 \x01(\x04\x12\x1f\n\x17redelegation_max_amount\x18\x03 \x01(\x04\x12\x12\n\nvote_slash\x18\x04 \x01(\t\x12\x14\n\x0cupload_slash\x18\x05 \x01(\t\x12\x15\n\rtimeout_slash\x18\x06 \x01(\tB6Z4github.com/KYVENetwork/chain/app/upgrades/v1_1/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_OLDBUNDLESPARAMS = _descriptor.Descriptor(
  name='OldBundlesParams',
  full_name='kyve.upgrades.v1beta1.OldBundlesParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upload_timeout', full_name='kyve.upgrades.v1beta1.OldBundlesParams.upload_timeout', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storage_cost', full_name='kyve.upgrades.v1beta1.OldBundlesParams.storage_cost', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network_fee', full_name='kyve.upgrades.v1beta1.OldBundlesParams.network_fee', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_points', full_name='kyve.upgrades.v1beta1.OldBundlesParams.max_points', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=241,
)


_OLDDELEGATIONPARAMS = _descriptor.Descriptor(
  name='OldDelegationParams',
  full_name='kyve.upgrades.v1beta1.OldDelegationParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unbonding_delegation_time', full_name='kyve.upgrades.v1beta1.OldDelegationParams.unbonding_delegation_time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='redelegation_cooldown', full_name='kyve.upgrades.v1beta1.OldDelegationParams.redelegation_cooldown', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='redelegation_max_amount', full_name='kyve.upgrades.v1beta1.OldDelegationParams.redelegation_max_amount', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vote_slash', full_name='kyve.upgrades.v1beta1.OldDelegationParams.vote_slash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upload_slash', full_name='kyve.upgrades.v1beta1.OldDelegationParams.upload_slash', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout_slash', full_name='kyve.upgrades.v1beta1.OldDelegationParams.timeout_slash', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=429,
)

DESCRIPTOR.message_types_by_name['OldBundlesParams'] = _OLDBUNDLESPARAMS
DESCRIPTOR.message_types_by_name['OldDelegationParams'] = _OLDDELEGATIONPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OldBundlesParams = _reflection.GeneratedProtocolMessageType('OldBundlesParams', (_message.Message,), dict(
  DESCRIPTOR = _OLDBUNDLESPARAMS,
  __module__ = 'kyve.upgrades.v1beta1.old_params_pb2'
  # @@protoc_insertion_point(class_scope:kyve.upgrades.v1beta1.OldBundlesParams)
  ))
_sym_db.RegisterMessage(OldBundlesParams)

OldDelegationParams = _reflection.GeneratedProtocolMessageType('OldDelegationParams', (_message.Message,), dict(
  DESCRIPTOR = _OLDDELEGATIONPARAMS,
  __module__ = 'kyve.upgrades.v1beta1.old_params_pb2'
  # @@protoc_insertion_point(class_scope:kyve.upgrades.v1beta1.OldDelegationParams)
  ))
_sym_db.RegisterMessage(OldDelegationParams)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z4github.com/KYVENetwork/chain/app/upgrades/v1_1/types'))
_OLDBUNDLESPARAMS.fields_by_name['storage_cost'].has_options = True
_OLDBUNDLESPARAMS.fields_by_name['storage_cost']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'))
# @@protoc_insertion_point(module_scope)
