# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/upgrades/v1beta1/old_stakers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/upgrades/v1beta1/old_stakers.proto',
  package='kyve.upgrades.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n\'kyve/upgrades/v1beta1/old_stakers.proto\x12\x15kyve.upgrades.v1beta1\"`\n\tOldStaker\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x12\n\ncommission\x18\x02 \x01(\t\x12\x0f\n\x07moniker\x18\x03 \x01(\t\x12\x0f\n\x07website\x18\x04 \x01(\t\x12\x0c\n\x04logo\x18\x05 \x01(\t\"d\n\x18OldCommissionChangeEntry\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0e\n\x06staker\x18\x02 \x01(\t\x12\x12\n\ncommission\x18\x03 \x01(\t\x12\x15\n\rcreation_date\x18\x04 \x01(\x03\x42\x36Z4github.com/KYVENetwork/chain/app/upgrades/v1_1/typesb\x06proto3')
)




_OLDSTAKER = _descriptor.Descriptor(
  name='OldStaker',
  full_name='kyve.upgrades.v1beta1.OldStaker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='kyve.upgrades.v1beta1.OldStaker.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commission', full_name='kyve.upgrades.v1beta1.OldStaker.commission', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moniker', full_name='kyve.upgrades.v1beta1.OldStaker.moniker', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='website', full_name='kyve.upgrades.v1beta1.OldStaker.website', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logo', full_name='kyve.upgrades.v1beta1.OldStaker.logo', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=162,
)


_OLDCOMMISSIONCHANGEENTRY = _descriptor.Descriptor(
  name='OldCommissionChangeEntry',
  full_name='kyve.upgrades.v1beta1.OldCommissionChangeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='kyve.upgrades.v1beta1.OldCommissionChangeEntry.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.upgrades.v1beta1.OldCommissionChangeEntry.staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commission', full_name='kyve.upgrades.v1beta1.OldCommissionChangeEntry.commission', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_date', full_name='kyve.upgrades.v1beta1.OldCommissionChangeEntry.creation_date', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=264,
)

DESCRIPTOR.message_types_by_name['OldStaker'] = _OLDSTAKER
DESCRIPTOR.message_types_by_name['OldCommissionChangeEntry'] = _OLDCOMMISSIONCHANGEENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OldStaker = _reflection.GeneratedProtocolMessageType('OldStaker', (_message.Message,), dict(
  DESCRIPTOR = _OLDSTAKER,
  __module__ = 'kyve.upgrades.v1beta1.old_stakers_pb2'
  # @@protoc_insertion_point(class_scope:kyve.upgrades.v1beta1.OldStaker)
  ))
_sym_db.RegisterMessage(OldStaker)

OldCommissionChangeEntry = _reflection.GeneratedProtocolMessageType('OldCommissionChangeEntry', (_message.Message,), dict(
  DESCRIPTOR = _OLDCOMMISSIONCHANGEENTRY,
  __module__ = 'kyve.upgrades.v1beta1.old_stakers_pb2'
  # @@protoc_insertion_point(class_scope:kyve.upgrades.v1beta1.OldCommissionChangeEntry)
  ))
_sym_db.RegisterMessage(OldCommissionChangeEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z4github.com/KYVENetwork/chain/app/upgrades/v1_1/types'))
# @@protoc_insertion_point(module_scope)
