# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/bundles/v1beta1/bundles.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/bundles/v1beta1/bundles.proto',
  package='kyve.bundles.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n\"kyve/bundles/v1beta1/bundles.proto\x12\x14kyve.bundles.v1beta1\x1a\x14gogoproto/gogo.proto\"\xe2\x02\n\x0e\x42undleProposal\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12\x12\n\nstorage_id\x18\x02 \x01(\t\x12\x10\n\x08uploader\x18\x03 \x01(\t\x12\x15\n\rnext_uploader\x18\x04 \x01(\t\x12\x11\n\tdata_size\x18\x05 \x01(\x04\x12\x13\n\x0b\x62undle_size\x18\x06 \x01(\x04\x12\x0e\n\x06to_key\x18\x07 \x01(\t\x12\x16\n\x0e\x62undle_summary\x18\x08 \x01(\t\x12\x11\n\tdata_hash\x18\t \x01(\t\x12\x12\n\nupdated_at\x18\n \x01(\x04\x12\x14\n\x0cvoters_valid\x18\x0b \x03(\t\x12\x16\n\x0evoters_invalid\x18\x0c \x03(\t\x12\x16\n\x0evoters_abstain\x18\r \x03(\t\x12\x10\n\x08\x66rom_key\x18\x0e \x01(\t\x12\x1b\n\x13storage_provider_id\x18\x0f \x01(\r\x12\x16\n\x0e\x63ompression_id\x18\x10 \x01(\r\"\xb5\x02\n\x0f\x46inalizedBundle\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x12\n\nstorage_id\x18\x03 \x01(\t\x12\x10\n\x08uploader\x18\x04 \x01(\t\x12\x12\n\nfrom_index\x18\x05 \x01(\x04\x12\x10\n\x08to_index\x18\x06 \x01(\x04\x12\x0e\n\x06to_key\x18\x07 \x01(\t\x12\x16\n\x0e\x62undle_summary\x18\x08 \x01(\t\x12\x11\n\tdata_hash\x18\t \x01(\t\x12\x37\n\x0c\x66inalized_at\x18\n \x01(\x0b\x32!.kyve.bundles.v1beta1.FinalizedAt\x12\x10\n\x08\x66rom_key\x18\x0b \x01(\t\x12\x1b\n\x13storage_provider_id\x18\x0c \x01(\r\x12\x16\n\x0e\x63ompression_id\x18\r \x01(\r\"0\n\x0b\x46inalizedAt\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04*\xbc\x01\n\x0c\x42undleStatus\x12\x1d\n\x19\x42UNDLE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13\x42UNDLE_STATUS_VALID\x10\x01\x12\x19\n\x15\x42UNDLE_STATUS_INVALID\x10\x02\x12\x1a\n\x16\x42UNDLE_STATUS_NO_FUNDS\x10\x03\x12\x1b\n\x17\x42UNDLE_STATUS_NO_QUORUM\x10\x04\x12\x1a\n\x16\x42UNDLE_STATUS_DISABLED\x10\x05\x1a\x04\x88\xa3\x1e\x00\x42.Z,github.com/KYVENetwork/chain/x/bundles/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])

_BUNDLESTATUS = _descriptor.EnumDescriptor(
  name='BundleStatus',
  full_name='kyve.bundles.v1beta1.BundleStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUNDLE_STATUS_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUNDLE_STATUS_VALID', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUNDLE_STATUS_INVALID', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUNDLE_STATUS_NO_FUNDS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUNDLE_STATUS_NO_QUORUM', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUNDLE_STATUS_DISABLED', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\000')),
  serialized_start=802,
  serialized_end=990,
)
_sym_db.RegisterEnumDescriptor(_BUNDLESTATUS)

BundleStatus = enum_type_wrapper.EnumTypeWrapper(_BUNDLESTATUS)
BUNDLE_STATUS_UNSPECIFIED = 0
BUNDLE_STATUS_VALID = 1
BUNDLE_STATUS_INVALID = 2
BUNDLE_STATUS_NO_FUNDS = 3
BUNDLE_STATUS_NO_QUORUM = 4
BUNDLE_STATUS_DISABLED = 5



_BUNDLEPROPOSAL = _descriptor.Descriptor(
  name='BundleProposal',
  full_name='kyve.bundles.v1beta1.BundleProposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='kyve.bundles.v1beta1.BundleProposal.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storage_id', full_name='kyve.bundles.v1beta1.BundleProposal.storage_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uploader', full_name='kyve.bundles.v1beta1.BundleProposal.uploader', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_uploader', full_name='kyve.bundles.v1beta1.BundleProposal.next_uploader', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_size', full_name='kyve.bundles.v1beta1.BundleProposal.data_size', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bundle_size', full_name='kyve.bundles.v1beta1.BundleProposal.bundle_size', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_key', full_name='kyve.bundles.v1beta1.BundleProposal.to_key', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bundle_summary', full_name='kyve.bundles.v1beta1.BundleProposal.bundle_summary', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_hash', full_name='kyve.bundles.v1beta1.BundleProposal.data_hash', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='kyve.bundles.v1beta1.BundleProposal.updated_at', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voters_valid', full_name='kyve.bundles.v1beta1.BundleProposal.voters_valid', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voters_invalid', full_name='kyve.bundles.v1beta1.BundleProposal.voters_invalid', index=11,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voters_abstain', full_name='kyve.bundles.v1beta1.BundleProposal.voters_abstain', index=12,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_key', full_name='kyve.bundles.v1beta1.BundleProposal.from_key', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storage_provider_id', full_name='kyve.bundles.v1beta1.BundleProposal.storage_provider_id', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compression_id', full_name='kyve.bundles.v1beta1.BundleProposal.compression_id', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=437,
)


_FINALIZEDBUNDLE = _descriptor.Descriptor(
  name='FinalizedBundle',
  full_name='kyve.bundles.v1beta1.FinalizedBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='kyve.bundles.v1beta1.FinalizedBundle.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='kyve.bundles.v1beta1.FinalizedBundle.id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storage_id', full_name='kyve.bundles.v1beta1.FinalizedBundle.storage_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uploader', full_name='kyve.bundles.v1beta1.FinalizedBundle.uploader', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_index', full_name='kyve.bundles.v1beta1.FinalizedBundle.from_index', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_index', full_name='kyve.bundles.v1beta1.FinalizedBundle.to_index', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_key', full_name='kyve.bundles.v1beta1.FinalizedBundle.to_key', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bundle_summary', full_name='kyve.bundles.v1beta1.FinalizedBundle.bundle_summary', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_hash', full_name='kyve.bundles.v1beta1.FinalizedBundle.data_hash', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finalized_at', full_name='kyve.bundles.v1beta1.FinalizedBundle.finalized_at', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_key', full_name='kyve.bundles.v1beta1.FinalizedBundle.from_key', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storage_provider_id', full_name='kyve.bundles.v1beta1.FinalizedBundle.storage_provider_id', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compression_id', full_name='kyve.bundles.v1beta1.FinalizedBundle.compression_id', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=749,
)


_FINALIZEDAT = _descriptor.Descriptor(
  name='FinalizedAt',
  full_name='kyve.bundles.v1beta1.FinalizedAt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='kyve.bundles.v1beta1.FinalizedAt.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='kyve.bundles.v1beta1.FinalizedAt.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=751,
  serialized_end=799,
)

_FINALIZEDBUNDLE.fields_by_name['finalized_at'].message_type = _FINALIZEDAT
DESCRIPTOR.message_types_by_name['BundleProposal'] = _BUNDLEPROPOSAL
DESCRIPTOR.message_types_by_name['FinalizedBundle'] = _FINALIZEDBUNDLE
DESCRIPTOR.message_types_by_name['FinalizedAt'] = _FINALIZEDAT
DESCRIPTOR.enum_types_by_name['BundleStatus'] = _BUNDLESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BundleProposal = _reflection.GeneratedProtocolMessageType('BundleProposal', (_message.Message,), dict(
  DESCRIPTOR = _BUNDLEPROPOSAL,
  __module__ = 'kyve.bundles.v1beta1.bundles_pb2'
  # @@protoc_insertion_point(class_scope:kyve.bundles.v1beta1.BundleProposal)
  ))
_sym_db.RegisterMessage(BundleProposal)

FinalizedBundle = _reflection.GeneratedProtocolMessageType('FinalizedBundle', (_message.Message,), dict(
  DESCRIPTOR = _FINALIZEDBUNDLE,
  __module__ = 'kyve.bundles.v1beta1.bundles_pb2'
  # @@protoc_insertion_point(class_scope:kyve.bundles.v1beta1.FinalizedBundle)
  ))
_sym_db.RegisterMessage(FinalizedBundle)

FinalizedAt = _reflection.GeneratedProtocolMessageType('FinalizedAt', (_message.Message,), dict(
  DESCRIPTOR = _FINALIZEDAT,
  __module__ = 'kyve.bundles.v1beta1.bundles_pb2'
  # @@protoc_insertion_point(class_scope:kyve.bundles.v1beta1.FinalizedAt)
  ))
_sym_db.RegisterMessage(FinalizedAt)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z,github.com/KYVENetwork/chain/x/bundles/types'))
_BUNDLESTATUS.has_options = True
_BUNDLESTATUS._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\000'))
# @@protoc_insertion_point(module_scope)
