# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/pool/v1beta1/pool.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/pool/v1beta1/pool.proto',
  package='kyve.pool.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n\x1ckyve/pool/v1beta1/pool.proto\x12\x11kyve.pool.v1beta1\x1a\x14gogoproto/gogo.proto\"C\n\x08Protocol\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x10\n\x08\x62inaries\x18\x02 \x01(\t\x12\x14\n\x0clast_upgrade\x18\x03 \x01(\x04\"X\n\x0bUpgradePlan\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x10\n\x08\x62inaries\x18\x02 \x01(\t\x12\x14\n\x0cscheduled_at\x18\x03 \x01(\x04\x12\x10\n\x08\x64uration\x18\x04 \x01(\x04\")\n\x06\x46under\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\"\x9d\x04\n\x04Pool\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07runtime\x18\x03 \x01(\t\x12\x0c\n\x04logo\x18\x04 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x05 \x01(\t\x12\x11\n\tstart_key\x18\x06 \x01(\t\x12\x13\n\x0b\x63urrent_key\x18\x07 \x01(\t\x12\x17\n\x0f\x63urrent_summary\x18\x08 \x01(\t\x12\x15\n\rcurrent_index\x18\t \x01(\x04\x12\x15\n\rtotal_bundles\x18\n \x01(\x04\x12\x17\n\x0fupload_interval\x18\x0b \x01(\x04\x12\x16\n\x0eoperating_cost\x18\x0c \x01(\x04\x12\x16\n\x0emin_delegation\x18\r \x01(\x04\x12\x17\n\x0fmax_bundle_size\x18\x0e \x01(\x04\x12\x10\n\x08\x64isabled\x18\x0f \x01(\x08\x12*\n\x07\x66unders\x18\x10 \x03(\x0b\x32\x19.kyve.pool.v1beta1.Funder\x12\x13\n\x0btotal_funds\x18\x11 \x01(\x04\x12-\n\x08protocol\x18\x12 \x01(\x0b\x32\x1b.kyve.pool.v1beta1.Protocol\x12\x34\n\x0cupgrade_plan\x18\x13 \x01(\x0b\x32\x1e.kyve.pool.v1beta1.UpgradePlan\x12#\n\x1b\x63urrent_storage_provider_id\x18\x14 \x01(\r\x12\x1e\n\x16\x63urrent_compression_id\x18\x15 \x01(\r*\xbd\x01\n\nPoolStatus\x12\x1b\n\x17POOL_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12POOL_STATUS_ACTIVE\x10\x01\x12\x18\n\x14POOL_STATUS_DISABLED\x10\x02\x12\x18\n\x14POOL_STATUS_NO_FUNDS\x10\x03\x12%\n!POOL_STATUS_NOT_ENOUGH_DELEGATION\x10\x04\x12\x19\n\x15POOL_STATUS_UPGRADING\x10\x05\x1a\x04\x88\xa3\x1e\x00\x42+Z)github.com/KYVENetwork/chain/x/pool/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])

_POOLSTATUS = _descriptor.EnumDescriptor(
  name='PoolStatus',
  full_name='kyve.pool.v1beta1.PoolStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POOL_STATUS_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POOL_STATUS_ACTIVE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POOL_STATUS_DISABLED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POOL_STATUS_NO_FUNDS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POOL_STATUS_NOT_ENOUGH_DELEGATION', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POOL_STATUS_UPGRADING', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\000')),
  serialized_start=820,
  serialized_end=1009,
)
_sym_db.RegisterEnumDescriptor(_POOLSTATUS)

PoolStatus = enum_type_wrapper.EnumTypeWrapper(_POOLSTATUS)
POOL_STATUS_UNSPECIFIED = 0
POOL_STATUS_ACTIVE = 1
POOL_STATUS_DISABLED = 2
POOL_STATUS_NO_FUNDS = 3
POOL_STATUS_NOT_ENOUGH_DELEGATION = 4
POOL_STATUS_UPGRADING = 5



_PROTOCOL = _descriptor.Descriptor(
  name='Protocol',
  full_name='kyve.pool.v1beta1.Protocol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='kyve.pool.v1beta1.Protocol.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binaries', full_name='kyve.pool.v1beta1.Protocol.binaries', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_upgrade', full_name='kyve.pool.v1beta1.Protocol.last_upgrade', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=140,
)


_UPGRADEPLAN = _descriptor.Descriptor(
  name='UpgradePlan',
  full_name='kyve.pool.v1beta1.UpgradePlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='kyve.pool.v1beta1.UpgradePlan.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binaries', full_name='kyve.pool.v1beta1.UpgradePlan.binaries', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scheduled_at', full_name='kyve.pool.v1beta1.UpgradePlan.scheduled_at', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='kyve.pool.v1beta1.UpgradePlan.duration', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=230,
)


_FUNDER = _descriptor.Descriptor(
  name='Funder',
  full_name='kyve.pool.v1beta1.Funder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='kyve.pool.v1beta1.Funder.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='kyve.pool.v1beta1.Funder.amount', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=273,
)


_POOL = _descriptor.Descriptor(
  name='Pool',
  full_name='kyve.pool.v1beta1.Pool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='kyve.pool.v1beta1.Pool.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='kyve.pool.v1beta1.Pool.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runtime', full_name='kyve.pool.v1beta1.Pool.runtime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logo', full_name='kyve.pool.v1beta1.Pool.logo', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='kyve.pool.v1beta1.Pool.config', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_key', full_name='kyve.pool.v1beta1.Pool.start_key', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_key', full_name='kyve.pool.v1beta1.Pool.current_key', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_summary', full_name='kyve.pool.v1beta1.Pool.current_summary', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_index', full_name='kyve.pool.v1beta1.Pool.current_index', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_bundles', full_name='kyve.pool.v1beta1.Pool.total_bundles', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upload_interval', full_name='kyve.pool.v1beta1.Pool.upload_interval', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operating_cost', full_name='kyve.pool.v1beta1.Pool.operating_cost', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_delegation', full_name='kyve.pool.v1beta1.Pool.min_delegation', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_bundle_size', full_name='kyve.pool.v1beta1.Pool.max_bundle_size', index=13,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disabled', full_name='kyve.pool.v1beta1.Pool.disabled', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='funders', full_name='kyve.pool.v1beta1.Pool.funders', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_funds', full_name='kyve.pool.v1beta1.Pool.total_funds', index=16,
      number=17, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='kyve.pool.v1beta1.Pool.protocol', index=17,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upgrade_plan', full_name='kyve.pool.v1beta1.Pool.upgrade_plan', index=18,
      number=19, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_storage_provider_id', full_name='kyve.pool.v1beta1.Pool.current_storage_provider_id', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_compression_id', full_name='kyve.pool.v1beta1.Pool.current_compression_id', index=20,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=817,
)

_POOL.fields_by_name['funders'].message_type = _FUNDER
_POOL.fields_by_name['protocol'].message_type = _PROTOCOL
_POOL.fields_by_name['upgrade_plan'].message_type = _UPGRADEPLAN
DESCRIPTOR.message_types_by_name['Protocol'] = _PROTOCOL
DESCRIPTOR.message_types_by_name['UpgradePlan'] = _UPGRADEPLAN
DESCRIPTOR.message_types_by_name['Funder'] = _FUNDER
DESCRIPTOR.message_types_by_name['Pool'] = _POOL
DESCRIPTOR.enum_types_by_name['PoolStatus'] = _POOLSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Protocol = _reflection.GeneratedProtocolMessageType('Protocol', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCOL,
  __module__ = 'kyve.pool.v1beta1.pool_pb2'
  # @@protoc_insertion_point(class_scope:kyve.pool.v1beta1.Protocol)
  ))
_sym_db.RegisterMessage(Protocol)

UpgradePlan = _reflection.GeneratedProtocolMessageType('UpgradePlan', (_message.Message,), dict(
  DESCRIPTOR = _UPGRADEPLAN,
  __module__ = 'kyve.pool.v1beta1.pool_pb2'
  # @@protoc_insertion_point(class_scope:kyve.pool.v1beta1.UpgradePlan)
  ))
_sym_db.RegisterMessage(UpgradePlan)

Funder = _reflection.GeneratedProtocolMessageType('Funder', (_message.Message,), dict(
  DESCRIPTOR = _FUNDER,
  __module__ = 'kyve.pool.v1beta1.pool_pb2'
  # @@protoc_insertion_point(class_scope:kyve.pool.v1beta1.Funder)
  ))
_sym_db.RegisterMessage(Funder)

Pool = _reflection.GeneratedProtocolMessageType('Pool', (_message.Message,), dict(
  DESCRIPTOR = _POOL,
  __module__ = 'kyve.pool.v1beta1.pool_pb2'
  # @@protoc_insertion_point(class_scope:kyve.pool.v1beta1.Pool)
  ))
_sym_db.RegisterMessage(Pool)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z)github.com/KYVENetwork/chain/x/pool/types'))
_POOLSTATUS.has_options = True
_POOLSTATUS._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), _b('\210\243\036\000'))
# @@protoc_insertion_point(module_scope)
