# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/global/v1beta1/global.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/global/v1beta1/global.proto',
  package='kyve.global.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n kyve/global/v1beta1/global.proto\x12\x13kyve.global.v1beta1\x1a\x14gogoproto/gogo.proto\"\xe4\x02\n\x06Params\x12\x45\n\rmin_gas_price\x18\x01 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x42\n\nburn_ratio\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x41\n\x0fgas_adjustments\x18\x03 \x03(\x0b\x32\".kyve.global.v1beta1.GasAdjustmentB\x04\xc8\xde\x1f\x00\x12\x39\n\x0bgas_refunds\x18\x04 \x03(\x0b\x32\x1e.kyve.global.v1beta1.GasRefundB\x04\xc8\xde\x1f\x00\x12Q\n\x19min_initial_deposit_ratio\x18\x05 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\"-\n\rGasAdjustment\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\"[\n\tGasRefund\x12\x0c\n\x04type\x18\x01 \x01(\t\x12@\n\x08\x66raction\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x42-Z+github.com/KYVENetwork/chain/x/global/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='kyve.global.v1beta1.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_gas_price', full_name='kyve.global.v1beta1.Params.min_gas_price', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='burn_ratio', full_name='kyve.global.v1beta1.Params.burn_ratio', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gas_adjustments', full_name='kyve.global.v1beta1.Params.gas_adjustments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gas_refunds', full_name='kyve.global.v1beta1.Params.gas_refunds', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_initial_deposit_ratio', full_name='kyve.global.v1beta1.Params.min_initial_deposit_ratio', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=436,
)


_GASADJUSTMENT = _descriptor.Descriptor(
  name='GasAdjustment',
  full_name='kyve.global.v1beta1.GasAdjustment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='kyve.global.v1beta1.GasAdjustment.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='kyve.global.v1beta1.GasAdjustment.amount', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=483,
)


_GASREFUND = _descriptor.Descriptor(
  name='GasRefund',
  full_name='kyve.global.v1beta1.GasRefund',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='kyve.global.v1beta1.GasRefund.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fraction', full_name='kyve.global.v1beta1.GasRefund.fraction', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=576,
)

_PARAMS.fields_by_name['gas_adjustments'].message_type = _GASADJUSTMENT
_PARAMS.fields_by_name['gas_refunds'].message_type = _GASREFUND
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['GasAdjustment'] = _GASADJUSTMENT
DESCRIPTOR.message_types_by_name['GasRefund'] = _GASREFUND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), dict(
  DESCRIPTOR = _PARAMS,
  __module__ = 'kyve.global.v1beta1.global_pb2'
  # @@protoc_insertion_point(class_scope:kyve.global.v1beta1.Params)
  ))
_sym_db.RegisterMessage(Params)

GasAdjustment = _reflection.GeneratedProtocolMessageType('GasAdjustment', (_message.Message,), dict(
  DESCRIPTOR = _GASADJUSTMENT,
  __module__ = 'kyve.global.v1beta1.global_pb2'
  # @@protoc_insertion_point(class_scope:kyve.global.v1beta1.GasAdjustment)
  ))
_sym_db.RegisterMessage(GasAdjustment)

GasRefund = _reflection.GeneratedProtocolMessageType('GasRefund', (_message.Message,), dict(
  DESCRIPTOR = _GASREFUND,
  __module__ = 'kyve.global.v1beta1.global_pb2'
  # @@protoc_insertion_point(class_scope:kyve.global.v1beta1.GasRefund)
  ))
_sym_db.RegisterMessage(GasRefund)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z+github.com/KYVENetwork/chain/x/global/types'))
_PARAMS.fields_by_name['min_gas_price'].has_options = True
_PARAMS.fields_by_name['min_gas_price']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'))
_PARAMS.fields_by_name['burn_ratio'].has_options = True
_PARAMS.fields_by_name['burn_ratio']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'))
_PARAMS.fields_by_name['gas_adjustments'].has_options = True
_PARAMS.fields_by_name['gas_adjustments']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_PARAMS.fields_by_name['gas_refunds'].has_options = True
_PARAMS.fields_by_name['gas_refunds']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_PARAMS.fields_by_name['min_initial_deposit_ratio'].has_options = True
_PARAMS.fields_by_name['min_initial_deposit_ratio']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'))
_GASREFUND.fields_by_name['fraction'].has_options = True
_GASREFUND.fields_by_name['fraction']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'))
# @@protoc_insertion_point(module_scope)
