# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/delegation/v1beta1/genesis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from kyve.delegation.v1beta1 import delegation_pb2 as kyve_dot_delegation_dot_v1beta1_dot_delegation__pb2
from kyve.delegation.v1beta1 import params_pb2 as kyve_dot_delegation_dot_v1beta1_dot_params__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/delegation/v1beta1/genesis.proto',
  package='kyve.delegation.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n%kyve/delegation/v1beta1/genesis.proto\x12\x17kyve.delegation.v1beta1\x1a\x14gogoproto/gogo.proto\x1a(kyve/delegation/v1beta1/delegation.proto\x1a$kyve/delegation/v1beta1/params.proto\"\xf6\x04\n\x0cGenesisState\x12\x35\n\x06params\x18\x01 \x01(\x0b\x32\x1f.kyve.delegation.v1beta1.ParamsB\x04\xc8\xde\x1f\x00\x12@\n\x0e\x64\x65legator_list\x18\x02 \x03(\x0b\x32\".kyve.delegation.v1beta1.DelegatorB\x04\xc8\xde\x1f\x00\x12M\n\x15\x64\x65legation_entry_list\x18\x03 \x03(\x0b\x32(.kyve.delegation.v1beta1.DelegationEntryB\x04\xc8\xde\x1f\x00\x12K\n\x14\x64\x65legation_data_list\x18\x04 \x03(\x0b\x32\'.kyve.delegation.v1beta1.DelegationDataB\x04\xc8\xde\x1f\x00\x12M\n\x15\x64\x65legation_slash_list\x18\x05 \x03(\x0b\x32(.kyve.delegation.v1beta1.DelegationSlashB\x04\xc8\xde\x1f\x00\x12\\\n\x1dundelegation_queue_entry_list\x18\x06 \x03(\x0b\x32/.kyve.delegation.v1beta1.UndelegationQueueEntryB\x04\xc8\xde\x1f\x00\x12K\n\x18queue_state_undelegation\x18\x07 \x01(\x0b\x32#.kyve.delegation.v1beta1.QueueStateB\x04\xc8\xde\x1f\x00\x12W\n\x1aredelegation_cooldown_list\x18\x08 \x03(\x0b\x32-.kyve.delegation.v1beta1.RedelegationCooldownB\x04\xc8\xde\x1f\x00\x42\x31Z/github.com/KYVENetwork/chain/x/delegation/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,kyve_dot_delegation_dot_v1beta1_dot_delegation__pb2.DESCRIPTOR,kyve_dot_delegation_dot_v1beta1_dot_params__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='kyve.delegation.v1beta1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='kyve.delegation.v1beta1.GenesisState.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delegator_list', full_name='kyve.delegation.v1beta1.GenesisState.delegator_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delegation_entry_list', full_name='kyve.delegation.v1beta1.GenesisState.delegation_entry_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delegation_data_list', full_name='kyve.delegation.v1beta1.GenesisState.delegation_data_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delegation_slash_list', full_name='kyve.delegation.v1beta1.GenesisState.delegation_slash_list', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='undelegation_queue_entry_list', full_name='kyve.delegation.v1beta1.GenesisState.undelegation_queue_entry_list', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queue_state_undelegation', full_name='kyve.delegation.v1beta1.GenesisState.queue_state_undelegation', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='redelegation_cooldown_list', full_name='kyve.delegation.v1beta1.GenesisState.redelegation_cooldown_list', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=799,
)

_GENESISSTATE.fields_by_name['params'].message_type = kyve_dot_delegation_dot_v1beta1_dot_params__pb2._PARAMS
_GENESISSTATE.fields_by_name['delegator_list'].message_type = kyve_dot_delegation_dot_v1beta1_dot_delegation__pb2._DELEGATOR
_GENESISSTATE.fields_by_name['delegation_entry_list'].message_type = kyve_dot_delegation_dot_v1beta1_dot_delegation__pb2._DELEGATIONENTRY
_GENESISSTATE.fields_by_name['delegation_data_list'].message_type = kyve_dot_delegation_dot_v1beta1_dot_delegation__pb2._DELEGATIONDATA
_GENESISSTATE.fields_by_name['delegation_slash_list'].message_type = kyve_dot_delegation_dot_v1beta1_dot_delegation__pb2._DELEGATIONSLASH
_GENESISSTATE.fields_by_name['undelegation_queue_entry_list'].message_type = kyve_dot_delegation_dot_v1beta1_dot_delegation__pb2._UNDELEGATIONQUEUEENTRY
_GENESISSTATE.fields_by_name['queue_state_undelegation'].message_type = kyve_dot_delegation_dot_v1beta1_dot_delegation__pb2._QUEUESTATE
_GENESISSTATE.fields_by_name['redelegation_cooldown_list'].message_type = kyve_dot_delegation_dot_v1beta1_dot_delegation__pb2._REDELEGATIONCOOLDOWN
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), dict(
  DESCRIPTOR = _GENESISSTATE,
  __module__ = 'kyve.delegation.v1beta1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.GenesisState)
  ))
_sym_db.RegisterMessage(GenesisState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z/github.com/KYVENetwork/chain/x/delegation/types'))
_GENESISSTATE.fields_by_name['params'].has_options = True
_GENESISSTATE.fields_by_name['params']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_GENESISSTATE.fields_by_name['delegator_list'].has_options = True
_GENESISSTATE.fields_by_name['delegator_list']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_GENESISSTATE.fields_by_name['delegation_entry_list'].has_options = True
_GENESISSTATE.fields_by_name['delegation_entry_list']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_GENESISSTATE.fields_by_name['delegation_data_list'].has_options = True
_GENESISSTATE.fields_by_name['delegation_data_list']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_GENESISSTATE.fields_by_name['delegation_slash_list'].has_options = True
_GENESISSTATE.fields_by_name['delegation_slash_list']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_GENESISSTATE.fields_by_name['undelegation_queue_entry_list'].has_options = True
_GENESISSTATE.fields_by_name['undelegation_queue_entry_list']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_GENESISSTATE.fields_by_name['queue_state_undelegation'].has_options = True
_GENESISSTATE.fields_by_name['queue_state_undelegation']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_GENESISSTATE.fields_by_name['redelegation_cooldown_list'].has_options = True
_GENESISSTATE.fields_by_name['redelegation_cooldown_list']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
# @@protoc_insertion_point(module_scope)
