# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/delegation/v1beta1/tx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/delegation/v1beta1/tx.proto',
  package='kyve.delegation.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n kyve/delegation/v1beta1/tx.proto\x12\x17kyve.delegation.v1beta1\x1a\x19\x63osmos_proto/cosmos.proto\">\n\x0bMsgDelegate\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0e\n\x06staker\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\"\x15\n\x13MsgDelegateResponse\"5\n\x12MsgWithdrawRewards\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0e\n\x06staker\x18\x02 \x01(\t\"\x1c\n\x1aMsgWithdrawRewardsResponse\"@\n\rMsgUndelegate\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0e\n\x06staker\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\"\x17\n\x15MsgUndelegateResponse\"X\n\rMsgRedelegate\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x13\n\x0b\x66rom_staker\x18\x02 \x01(\t\x12\x11\n\tto_staker\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x04\"\x17\n\x15MsgRedelegateResponse\"O\n\x0fMsgUpdateParams\x12+\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressString\x12\x0f\n\x07payload\x18\x02 \x01(\t\"\x19\n\x17MsgUpdateParamsResponse2\x92\x04\n\x03Msg\x12^\n\x08\x44\x65legate\x12$.kyve.delegation.v1beta1.MsgDelegate\x1a,.kyve.delegation.v1beta1.MsgDelegateResponse\x12s\n\x0fWithdrawRewards\x12+.kyve.delegation.v1beta1.MsgWithdrawRewards\x1a\x33.kyve.delegation.v1beta1.MsgWithdrawRewardsResponse\x12\x64\n\nUndelegate\x12&.kyve.delegation.v1beta1.MsgUndelegate\x1a..kyve.delegation.v1beta1.MsgUndelegateResponse\x12\x64\n\nRedelegate\x12&.kyve.delegation.v1beta1.MsgRedelegate\x1a..kyve.delegation.v1beta1.MsgRedelegateResponse\x12j\n\x0cUpdateParams\x12(.kyve.delegation.v1beta1.MsgUpdateParams\x1a\x30.kyve.delegation.v1beta1.MsgUpdateParamsResponseB1Z/github.com/KYVENetwork/chain/x/delegation/typesb\x06proto3')
  ,
  dependencies=[cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,])




_MSGDELEGATE = _descriptor.Descriptor(
  name='MsgDelegate',
  full_name='kyve.delegation.v1beta1.MsgDelegate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='creator', full_name='kyve.delegation.v1beta1.MsgDelegate.creator', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.delegation.v1beta1.MsgDelegate.staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='kyve.delegation.v1beta1.MsgDelegate.amount', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=150,
)


_MSGDELEGATERESPONSE = _descriptor.Descriptor(
  name='MsgDelegateResponse',
  full_name='kyve.delegation.v1beta1.MsgDelegateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=173,
)


_MSGWITHDRAWREWARDS = _descriptor.Descriptor(
  name='MsgWithdrawRewards',
  full_name='kyve.delegation.v1beta1.MsgWithdrawRewards',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='creator', full_name='kyve.delegation.v1beta1.MsgWithdrawRewards.creator', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.delegation.v1beta1.MsgWithdrawRewards.staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=228,
)


_MSGWITHDRAWREWARDSRESPONSE = _descriptor.Descriptor(
  name='MsgWithdrawRewardsResponse',
  full_name='kyve.delegation.v1beta1.MsgWithdrawRewardsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=258,
)


_MSGUNDELEGATE = _descriptor.Descriptor(
  name='MsgUndelegate',
  full_name='kyve.delegation.v1beta1.MsgUndelegate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='creator', full_name='kyve.delegation.v1beta1.MsgUndelegate.creator', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.delegation.v1beta1.MsgUndelegate.staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='kyve.delegation.v1beta1.MsgUndelegate.amount', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=324,
)


_MSGUNDELEGATERESPONSE = _descriptor.Descriptor(
  name='MsgUndelegateResponse',
  full_name='kyve.delegation.v1beta1.MsgUndelegateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=349,
)


_MSGREDELEGATE = _descriptor.Descriptor(
  name='MsgRedelegate',
  full_name='kyve.delegation.v1beta1.MsgRedelegate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='creator', full_name='kyve.delegation.v1beta1.MsgRedelegate.creator', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_staker', full_name='kyve.delegation.v1beta1.MsgRedelegate.from_staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_staker', full_name='kyve.delegation.v1beta1.MsgRedelegate.to_staker', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='kyve.delegation.v1beta1.MsgRedelegate.amount', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=439,
)


_MSGREDELEGATERESPONSE = _descriptor.Descriptor(
  name='MsgRedelegateResponse',
  full_name='kyve.delegation.v1beta1.MsgRedelegateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=464,
)


_MSGUPDATEPARAMS = _descriptor.Descriptor(
  name='MsgUpdateParams',
  full_name='kyve.delegation.v1beta1.MsgUpdateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authority', full_name='kyve.delegation.v1beta1.MsgUpdateParams.authority', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\322\264-\024cosmos.AddressString')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='kyve.delegation.v1beta1.MsgUpdateParams.payload', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=545,
)


_MSGUPDATEPARAMSRESPONSE = _descriptor.Descriptor(
  name='MsgUpdateParamsResponse',
  full_name='kyve.delegation.v1beta1.MsgUpdateParamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=572,
)

DESCRIPTOR.message_types_by_name['MsgDelegate'] = _MSGDELEGATE
DESCRIPTOR.message_types_by_name['MsgDelegateResponse'] = _MSGDELEGATERESPONSE
DESCRIPTOR.message_types_by_name['MsgWithdrawRewards'] = _MSGWITHDRAWREWARDS
DESCRIPTOR.message_types_by_name['MsgWithdrawRewardsResponse'] = _MSGWITHDRAWREWARDSRESPONSE
DESCRIPTOR.message_types_by_name['MsgUndelegate'] = _MSGUNDELEGATE
DESCRIPTOR.message_types_by_name['MsgUndelegateResponse'] = _MSGUNDELEGATERESPONSE
DESCRIPTOR.message_types_by_name['MsgRedelegate'] = _MSGREDELEGATE
DESCRIPTOR.message_types_by_name['MsgRedelegateResponse'] = _MSGREDELEGATERESPONSE
DESCRIPTOR.message_types_by_name['MsgUpdateParams'] = _MSGUPDATEPARAMS
DESCRIPTOR.message_types_by_name['MsgUpdateParamsResponse'] = _MSGUPDATEPARAMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgDelegate = _reflection.GeneratedProtocolMessageType('MsgDelegate', (_message.Message,), dict(
  DESCRIPTOR = _MSGDELEGATE,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgDelegate)
  ))
_sym_db.RegisterMessage(MsgDelegate)

MsgDelegateResponse = _reflection.GeneratedProtocolMessageType('MsgDelegateResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGDELEGATERESPONSE,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgDelegateResponse)
  ))
_sym_db.RegisterMessage(MsgDelegateResponse)

MsgWithdrawRewards = _reflection.GeneratedProtocolMessageType('MsgWithdrawRewards', (_message.Message,), dict(
  DESCRIPTOR = _MSGWITHDRAWREWARDS,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgWithdrawRewards)
  ))
_sym_db.RegisterMessage(MsgWithdrawRewards)

MsgWithdrawRewardsResponse = _reflection.GeneratedProtocolMessageType('MsgWithdrawRewardsResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGWITHDRAWREWARDSRESPONSE,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgWithdrawRewardsResponse)
  ))
_sym_db.RegisterMessage(MsgWithdrawRewardsResponse)

MsgUndelegate = _reflection.GeneratedProtocolMessageType('MsgUndelegate', (_message.Message,), dict(
  DESCRIPTOR = _MSGUNDELEGATE,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgUndelegate)
  ))
_sym_db.RegisterMessage(MsgUndelegate)

MsgUndelegateResponse = _reflection.GeneratedProtocolMessageType('MsgUndelegateResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGUNDELEGATERESPONSE,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgUndelegateResponse)
  ))
_sym_db.RegisterMessage(MsgUndelegateResponse)

MsgRedelegate = _reflection.GeneratedProtocolMessageType('MsgRedelegate', (_message.Message,), dict(
  DESCRIPTOR = _MSGREDELEGATE,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgRedelegate)
  ))
_sym_db.RegisterMessage(MsgRedelegate)

MsgRedelegateResponse = _reflection.GeneratedProtocolMessageType('MsgRedelegateResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGREDELEGATERESPONSE,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgRedelegateResponse)
  ))
_sym_db.RegisterMessage(MsgRedelegateResponse)

MsgUpdateParams = _reflection.GeneratedProtocolMessageType('MsgUpdateParams', (_message.Message,), dict(
  DESCRIPTOR = _MSGUPDATEPARAMS,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgUpdateParams)
  ))
_sym_db.RegisterMessage(MsgUpdateParams)

MsgUpdateParamsResponse = _reflection.GeneratedProtocolMessageType('MsgUpdateParamsResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGUPDATEPARAMSRESPONSE,
  __module__ = 'kyve.delegation.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:kyve.delegation.v1beta1.MsgUpdateParamsResponse)
  ))
_sym_db.RegisterMessage(MsgUpdateParamsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z/github.com/KYVENetwork/chain/x/delegation/types'))
_MSGUPDATEPARAMS.fields_by_name['authority'].has_options = True
_MSGUPDATEPARAMS.fields_by_name['authority']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\322\264-\024cosmos.AddressString'))

_MSG = _descriptor.ServiceDescriptor(
  name='Msg',
  full_name='kyve.delegation.v1beta1.Msg',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=575,
  serialized_end=1105,
  methods=[
  _descriptor.MethodDescriptor(
    name='Delegate',
    full_name='kyve.delegation.v1beta1.Msg.Delegate',
    index=0,
    containing_service=None,
    input_type=_MSGDELEGATE,
    output_type=_MSGDELEGATERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WithdrawRewards',
    full_name='kyve.delegation.v1beta1.Msg.WithdrawRewards',
    index=1,
    containing_service=None,
    input_type=_MSGWITHDRAWREWARDS,
    output_type=_MSGWITHDRAWREWARDSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Undelegate',
    full_name='kyve.delegation.v1beta1.Msg.Undelegate',
    index=2,
    containing_service=None,
    input_type=_MSGUNDELEGATE,
    output_type=_MSGUNDELEGATERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Redelegate',
    full_name='kyve.delegation.v1beta1.Msg.Redelegate',
    index=3,
    containing_service=None,
    input_type=_MSGREDELEGATE,
    output_type=_MSGREDELEGATERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateParams',
    full_name='kyve.delegation.v1beta1.Msg.UpdateParams',
    index=4,
    containing_service=None,
    input_type=_MSGUPDATEPARAMS,
    output_type=_MSGUPDATEPARAMSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name['Msg'] = _MSG

# @@protoc_insertion_point(module_scope)
