# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/stakers/v1beta1/events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from kyve.stakers.v1beta1 import params_pb2 as kyve_dot_stakers_dot_v1beta1_dot_params__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/stakers/v1beta1/events.proto',
  package='kyve.stakers.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n!kyve/stakers/v1beta1/events.proto\x12\x14kyve.stakers.v1beta1\x1a\x14gogoproto/gogo.proto\x1a!kyve/stakers/v1beta1/params.proto\"\x94\x01\n\x11\x45ventUpdateParams\x12\x36\n\nold_params\x18\x01 \x01(\x0b\x32\x1c.kyve.stakers.v1beta1.ParamsB\x04\xc8\xde\x1f\x00\x12\x36\n\nnew_params\x18\x02 \x01(\x0b\x32\x1c.kyve.stakers.v1beta1.ParamsB\x04\xc8\xde\x1f\x00\x12\x0f\n\x07payload\x18\x03 \x01(\t\"w\n\x11\x45ventCreateStaker\x12\x0e\n\x06staker\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x12\x42\n\ncommission\x18\x03 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\"\x84\x01\n\x13\x45ventUpdateMetadata\x12\x0e\n\x06staker\x18\x01 \x01(\t\x12\x0f\n\x07moniker\x18\x02 \x01(\t\x12\x0f\n\x07website\x18\x03 \x01(\t\x12\x10\n\x08identity\x18\x04 \x01(\t\x12\x18\n\x10security_contact\x18\x05 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x06 \x01(\t\"k\n\x15\x45ventUpdateCommission\x12\x0e\n\x06staker\x18\x01 \x01(\t\x12\x42\n\ncommission\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\"T\n\rEventJoinPool\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12\x0e\n\x06staker\x18\x02 \x01(\t\x12\x12\n\nvaladdress\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x04\"1\n\x0e\x45ventLeavePool\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12\x0e\n\x06staker\x18\x02 \x01(\tB.Z,github.com/KYVENetwork/chain/x/stakers/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,kyve_dot_stakers_dot_v1beta1_dot_params__pb2.DESCRIPTOR,])




_EVENTUPDATEPARAMS = _descriptor.Descriptor(
  name='EventUpdateParams',
  full_name='kyve.stakers.v1beta1.EventUpdateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='old_params', full_name='kyve.stakers.v1beta1.EventUpdateParams.old_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_params', full_name='kyve.stakers.v1beta1.EventUpdateParams.new_params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='kyve.stakers.v1beta1.EventUpdateParams.payload', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=265,
)


_EVENTCREATESTAKER = _descriptor.Descriptor(
  name='EventCreateStaker',
  full_name='kyve.stakers.v1beta1.EventCreateStaker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.stakers.v1beta1.EventCreateStaker.staker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='kyve.stakers.v1beta1.EventCreateStaker.amount', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commission', full_name='kyve.stakers.v1beta1.EventCreateStaker.commission', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=386,
)


_EVENTUPDATEMETADATA = _descriptor.Descriptor(
  name='EventUpdateMetadata',
  full_name='kyve.stakers.v1beta1.EventUpdateMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.stakers.v1beta1.EventUpdateMetadata.staker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moniker', full_name='kyve.stakers.v1beta1.EventUpdateMetadata.moniker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='website', full_name='kyve.stakers.v1beta1.EventUpdateMetadata.website', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identity', full_name='kyve.stakers.v1beta1.EventUpdateMetadata.identity', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='security_contact', full_name='kyve.stakers.v1beta1.EventUpdateMetadata.security_contact', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='kyve.stakers.v1beta1.EventUpdateMetadata.details', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=521,
)


_EVENTUPDATECOMMISSION = _descriptor.Descriptor(
  name='EventUpdateCommission',
  full_name='kyve.stakers.v1beta1.EventUpdateCommission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.stakers.v1beta1.EventUpdateCommission.staker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commission', full_name='kyve.stakers.v1beta1.EventUpdateCommission.commission', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=630,
)


_EVENTJOINPOOL = _descriptor.Descriptor(
  name='EventJoinPool',
  full_name='kyve.stakers.v1beta1.EventJoinPool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='kyve.stakers.v1beta1.EventJoinPool.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.stakers.v1beta1.EventJoinPool.staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valaddress', full_name='kyve.stakers.v1beta1.EventJoinPool.valaddress', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='kyve.stakers.v1beta1.EventJoinPool.amount', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=632,
  serialized_end=716,
)


_EVENTLEAVEPOOL = _descriptor.Descriptor(
  name='EventLeavePool',
  full_name='kyve.stakers.v1beta1.EventLeavePool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='kyve.stakers.v1beta1.EventLeavePool.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.stakers.v1beta1.EventLeavePool.staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=767,
)

_EVENTUPDATEPARAMS.fields_by_name['old_params'].message_type = kyve_dot_stakers_dot_v1beta1_dot_params__pb2._PARAMS
_EVENTUPDATEPARAMS.fields_by_name['new_params'].message_type = kyve_dot_stakers_dot_v1beta1_dot_params__pb2._PARAMS
DESCRIPTOR.message_types_by_name['EventUpdateParams'] = _EVENTUPDATEPARAMS
DESCRIPTOR.message_types_by_name['EventCreateStaker'] = _EVENTCREATESTAKER
DESCRIPTOR.message_types_by_name['EventUpdateMetadata'] = _EVENTUPDATEMETADATA
DESCRIPTOR.message_types_by_name['EventUpdateCommission'] = _EVENTUPDATECOMMISSION
DESCRIPTOR.message_types_by_name['EventJoinPool'] = _EVENTJOINPOOL
DESCRIPTOR.message_types_by_name['EventLeavePool'] = _EVENTLEAVEPOOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventUpdateParams = _reflection.GeneratedProtocolMessageType('EventUpdateParams', (_message.Message,), dict(
  DESCRIPTOR = _EVENTUPDATEPARAMS,
  __module__ = 'kyve.stakers.v1beta1.events_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.EventUpdateParams)
  ))
_sym_db.RegisterMessage(EventUpdateParams)

EventCreateStaker = _reflection.GeneratedProtocolMessageType('EventCreateStaker', (_message.Message,), dict(
  DESCRIPTOR = _EVENTCREATESTAKER,
  __module__ = 'kyve.stakers.v1beta1.events_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.EventCreateStaker)
  ))
_sym_db.RegisterMessage(EventCreateStaker)

EventUpdateMetadata = _reflection.GeneratedProtocolMessageType('EventUpdateMetadata', (_message.Message,), dict(
  DESCRIPTOR = _EVENTUPDATEMETADATA,
  __module__ = 'kyve.stakers.v1beta1.events_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.EventUpdateMetadata)
  ))
_sym_db.RegisterMessage(EventUpdateMetadata)

EventUpdateCommission = _reflection.GeneratedProtocolMessageType('EventUpdateCommission', (_message.Message,), dict(
  DESCRIPTOR = _EVENTUPDATECOMMISSION,
  __module__ = 'kyve.stakers.v1beta1.events_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.EventUpdateCommission)
  ))
_sym_db.RegisterMessage(EventUpdateCommission)

EventJoinPool = _reflection.GeneratedProtocolMessageType('EventJoinPool', (_message.Message,), dict(
  DESCRIPTOR = _EVENTJOINPOOL,
  __module__ = 'kyve.stakers.v1beta1.events_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.EventJoinPool)
  ))
_sym_db.RegisterMessage(EventJoinPool)

EventLeavePool = _reflection.GeneratedProtocolMessageType('EventLeavePool', (_message.Message,), dict(
  DESCRIPTOR = _EVENTLEAVEPOOL,
  __module__ = 'kyve.stakers.v1beta1.events_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.EventLeavePool)
  ))
_sym_db.RegisterMessage(EventLeavePool)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z,github.com/KYVENetwork/chain/x/stakers/types'))
_EVENTUPDATEPARAMS.fields_by_name['old_params'].has_options = True
_EVENTUPDATEPARAMS.fields_by_name['old_params']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_EVENTUPDATEPARAMS.fields_by_name['new_params'].has_options = True
_EVENTUPDATEPARAMS.fields_by_name['new_params']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310\336\037\000'))
_EVENTCREATESTAKER.fields_by_name['commission'].has_options = True
_EVENTCREATESTAKER.fields_by_name['commission']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'))
_EVENTUPDATECOMMISSION.fields_by_name['commission'].has_options = True
_EVENTUPDATECOMMISSION.fields_by_name['commission']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'))
# @@protoc_insertion_point(module_scope)
