# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyve/stakers/v1beta1/stakers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kyve/stakers/v1beta1/stakers.proto',
  package='kyve.stakers.v1beta1',
  syntax='proto3',
  serialized_pb=_b('\n\"kyve/stakers/v1beta1/stakers.proto\x12\x14kyve.stakers.v1beta1\x1a\x14gogoproto/gogo.proto\"\xbc\x01\n\x06Staker\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x42\n\ncommission\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x0f\n\x07moniker\x18\x03 \x01(\t\x12\x0f\n\x07website\x18\x04 \x01(\t\x12\x10\n\x08identity\x18\x05 \x01(\t\x12\x18\n\x10security_contact\x18\x06 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x07 \x01(\t\"e\n\nValaccount\x12\x0f\n\x07pool_id\x18\x01 \x01(\x04\x12\x0e\n\x06staker\x18\x02 \x01(\t\x12\x12\n\nvaladdress\x18\x03 \x01(\t\x12\x0e\n\x06points\x18\x04 \x01(\x04\x12\x12\n\nis_leaving\x18\x05 \x01(\x08\"\x91\x01\n\x15\x43ommissionChangeEntry\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0e\n\x06staker\x18\x02 \x01(\t\x12\x42\n\ncommission\x18\x03 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x15\n\rcreation_date\x18\x04 \x01(\x03\"W\n\x0eLeavePoolEntry\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0e\n\x06staker\x18\x02 \x01(\t\x12\x0f\n\x07pool_id\x18\x03 \x01(\x04\x12\x15\n\rcreation_date\x18\x04 \x01(\x03\"3\n\nQueueState\x12\x11\n\tlow_index\x18\x01 \x01(\x04\x12\x12\n\nhigh_index\x18\x02 \x01(\x04\x42.Z,github.com/KYVENetwork/chain/x/stakers/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_STAKER = _descriptor.Descriptor(
  name='Staker',
  full_name='kyve.stakers.v1beta1.Staker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='kyve.stakers.v1beta1.Staker.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commission', full_name='kyve.stakers.v1beta1.Staker.commission', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moniker', full_name='kyve.stakers.v1beta1.Staker.moniker', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='website', full_name='kyve.stakers.v1beta1.Staker.website', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identity', full_name='kyve.stakers.v1beta1.Staker.identity', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='security_contact', full_name='kyve.stakers.v1beta1.Staker.security_contact', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='kyve.stakers.v1beta1.Staker.details', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=271,
)


_VALACCOUNT = _descriptor.Descriptor(
  name='Valaccount',
  full_name='kyve.stakers.v1beta1.Valaccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='kyve.stakers.v1beta1.Valaccount.pool_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.stakers.v1beta1.Valaccount.staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valaddress', full_name='kyve.stakers.v1beta1.Valaccount.valaddress', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='kyve.stakers.v1beta1.Valaccount.points', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_leaving', full_name='kyve.stakers.v1beta1.Valaccount.is_leaving', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=374,
)


_COMMISSIONCHANGEENTRY = _descriptor.Descriptor(
  name='CommissionChangeEntry',
  full_name='kyve.stakers.v1beta1.CommissionChangeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='kyve.stakers.v1beta1.CommissionChangeEntry.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.stakers.v1beta1.CommissionChangeEntry.staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commission', full_name='kyve.stakers.v1beta1.CommissionChangeEntry.commission', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_date', full_name='kyve.stakers.v1beta1.CommissionChangeEntry.creation_date', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=522,
)


_LEAVEPOOLENTRY = _descriptor.Descriptor(
  name='LeavePoolEntry',
  full_name='kyve.stakers.v1beta1.LeavePoolEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='kyve.stakers.v1beta1.LeavePoolEntry.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staker', full_name='kyve.stakers.v1beta1.LeavePoolEntry.staker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pool_id', full_name='kyve.stakers.v1beta1.LeavePoolEntry.pool_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_date', full_name='kyve.stakers.v1beta1.LeavePoolEntry.creation_date', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=611,
)


_QUEUESTATE = _descriptor.Descriptor(
  name='QueueState',
  full_name='kyve.stakers.v1beta1.QueueState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='low_index', full_name='kyve.stakers.v1beta1.QueueState.low_index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high_index', full_name='kyve.stakers.v1beta1.QueueState.high_index', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=664,
)

DESCRIPTOR.message_types_by_name['Staker'] = _STAKER
DESCRIPTOR.message_types_by_name['Valaccount'] = _VALACCOUNT
DESCRIPTOR.message_types_by_name['CommissionChangeEntry'] = _COMMISSIONCHANGEENTRY
DESCRIPTOR.message_types_by_name['LeavePoolEntry'] = _LEAVEPOOLENTRY
DESCRIPTOR.message_types_by_name['QueueState'] = _QUEUESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Staker = _reflection.GeneratedProtocolMessageType('Staker', (_message.Message,), dict(
  DESCRIPTOR = _STAKER,
  __module__ = 'kyve.stakers.v1beta1.stakers_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.Staker)
  ))
_sym_db.RegisterMessage(Staker)

Valaccount = _reflection.GeneratedProtocolMessageType('Valaccount', (_message.Message,), dict(
  DESCRIPTOR = _VALACCOUNT,
  __module__ = 'kyve.stakers.v1beta1.stakers_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.Valaccount)
  ))
_sym_db.RegisterMessage(Valaccount)

CommissionChangeEntry = _reflection.GeneratedProtocolMessageType('CommissionChangeEntry', (_message.Message,), dict(
  DESCRIPTOR = _COMMISSIONCHANGEENTRY,
  __module__ = 'kyve.stakers.v1beta1.stakers_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.CommissionChangeEntry)
  ))
_sym_db.RegisterMessage(CommissionChangeEntry)

LeavePoolEntry = _reflection.GeneratedProtocolMessageType('LeavePoolEntry', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEPOOLENTRY,
  __module__ = 'kyve.stakers.v1beta1.stakers_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.LeavePoolEntry)
  ))
_sym_db.RegisterMessage(LeavePoolEntry)

QueueState = _reflection.GeneratedProtocolMessageType('QueueState', (_message.Message,), dict(
  DESCRIPTOR = _QUEUESTATE,
  __module__ = 'kyve.stakers.v1beta1.stakers_pb2'
  # @@protoc_insertion_point(class_scope:kyve.stakers.v1beta1.QueueState)
  ))
_sym_db.RegisterMessage(QueueState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z,github.com/KYVENetwork/chain/x/stakers/types'))
_STAKER.fields_by_name['commission'].has_options = True
_STAKER.fields_by_name['commission']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'))
_COMMISSIONCHANGEENTRY.fields_by_name['commission'].has_options = True
_COMMISSIONCHANGEENTRY.fields_by_name['commission']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'))
# @@protoc_insertion_point(module_scope)
